### ISSUE TITLE
希望增加发送敏感词被拦截后的提示语

### ISSUE THREAD

**Issue by NealScx** [CrazyBoyM/nonebot-plugin-drawer#2]
收到敏感信息后![image](https://user-images.githubusercontent.com/85844254/185399311-429e2280-52d6-4170-9d6f-ea1f0dd085d7.png)

依然是正常回复![image](https://user-images.githubusercontent.com/85844254/185399595-3558a2ee-d99c-48d5-a998-80f13b686de2.png)

**Comment by CrazyBoyM** [comment]
感谢建议，已添加。

**Comment by NealScx** [comment]
> 感谢建议，已添加。

不知道为什么   使用nbcli 更新还是老版本
