### ISSUE TITLE
多条绘画指令 只会执行最后一条

### ISSUE THREAD

**Issue by NealScx** [CrazyBoyM/nonebot-plugin-drawer#3]
![image](https://user-images.githubusercontent.com/85844254/185404286-9f2a0f02-4b07-430c-896a-d4d88575427b.png)
前面的指令会报错
![image](https://user-images.githubusercontent.com/85844254/185404512-eedb243e-cade-4772-a0ef-4efba7c684a3.png)

**Comment by CrazyBoyM** [comment]
我这里实验多条任务是支持的，没能复现这个错误.
