### ISSUE TITLE
wenxin_cd_time 技能冷却不起作用

### ISSUE THREAD

**Issue by billyosoror** [CrazyBoyM/nonebot-plugin-drawer#4]
我在.env配置文件添加该参数，代码不起作用

**Comment by CrazyBoyM** [comment]
对管理员不起作用。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月21日(周日) 上午10:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CrazyBoyM/nonebot-plugin-drawer] wenxin_cd_time 技能冷却不起作用 (Issue #4)




 
我在.env配置文件添加该参数，代码不起作用
 
&mdash;

**Comment by billyosoror** [comment]
我用其他非管理员号测试也不起作用

**Comment by CrazyBoyM** [comment]
ok，我中午会测试一下


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月21日(周日) 上午10:49
收件人: ***@***.***&gt;;
抄送: &quot;Ke ***@***.******@***.***&gt;;
主题: Re: [CrazyBoyM/nonebot-plugin-drawer] wenxin_cd_time 技能冷却不起作用 (Issue #4)




 
我用其他非管理员号测试也不起作用
 
&mdash;

**Comment by CrazyBoyM** [comment]
已经fix
