### ISSUE TITLE
【报错】任意关键词都是违禁词

### ISSUE THREAD

**Issue by Agnes4m** [CrazyBoyM/nonebot-plugin-drawer#5]
如题，任意关键词都提示违禁
![image](https://user-images.githubusercontent.com/70925546/188081876-0d9d88cd-8eb5-4653-9dc0-845eace48f28.png)
![image](https://user-images.githubusercontent.com/70925546/188081904-c8e1e71a-9e76-4840-baae-bc68a7fcd557.png)
![image](https://user-images.githubusercontent.com/70925546/188081920-03edfc16-92f1-40ae-9272-66f09a4c8616.png)

**Comment by CrazyBoyM** [comment]
这个是文心的服务器比较忙时会出现。
