### ISSUE TITLE
建议更新最新

### ISSUE THREAD

**Issue by liuzj288** [CrazyBoyM/nonebot-plugin-drawer#8]
![image](https://user-images.githubusercontent.com/13833404/193967369-94919f4b-7dd3-4be5-b70b-887a9fa767cf.png)

另api到日上限的提示仍然是违规
![image](https://user-images.githubusercontent.com/13833404/194010875-bab55f4c-23bc-410b-821b-163f7e91ee47.png)
![image](https://user-images.githubusercontent.com/13833404/194010931-5cbd037e-0998-4ea6-b43a-8206bfda9e62.png)

**Comment by CrazyBoyM** [comment]
感谢，已经合并PR.
